Repository FIRSTPLATO/x45c, pull requests merged in 2021-10, with the labels that each got.

#2 Update for documentation and readme.md
  README.md
  README_en.md
  docs/efi.md
  docs/firmware.md
  docs/hardware.md
  docs/index.md
  docs/index_en.md
  docs/macos.md
  docs/os.md
  docs/referensi.md
  docs/spesifikasi.md
  docs/ubuntu.md
  docs/windows.md
Labels: documentation, hacktoberfest-accepted, firstplato

#3 Update documentation
  docs/firmware.md
  docs/img/asus.png
  docs/img/firmware.png
  docs/img/info.md
  docs/index.md
  docs/spesifikasi.md
Labels: documentation, enhancement, hacktoberfest-accepted, firstplato

#4 Fix some link error in documentation
  System/macos/info.md
  System/ubuntu/info.md
  System/windows/info.md
  docs/firmware.md
  docs/index.md
  docs/spesifikasi.md
Labels: documentation, hacktoberfest-accepted, firstplato

#6 Documentation for hardware upgrade
  docs/hardware.md
  docs/referensi.md
Labels: documentation, hacktoberfest-accepted, firstplato

#7 Docs for EFI and OS list
  README.md
  docs/os.md
Labels: documentation, enhancement, firstplato, efi, system
